default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: premium_2024_development
test:
  <<: *default
  database: premium_2024_test

production:
  <<: *default
  database: premium_2024_production
