development: 
  api_key: "QDKO8E6VGCU206L96YZO1LSLBB4ETMO2"
  secret_key: "VTXMZPAYK1YGVUYV"
  way2sms_url: "https://www.sms4india.com"
  sender_id: "PREMUM"

production:  
  api_key: <%= ENV["API_KEY"] %>
  secret_key: <%= ENV["WAY2SMS_SECRET_KEY"] %>
  way2sms_url: <%= ENV["WAY2SMS_URL"] %>
  sender_id: <%= ENV["SENDER_ID"] %>